[package]
name = "vrchatapi"
version = "1.7.6"
authors = ["OpenAPI Generator team and contributors"]
license = "MIT"
edition = "2018"
description="VRChat API Library for Rust"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^2.2"
reqwest = "~0.9"

[dev-dependencies]
